name: Build and Push to Local Registry

on:
  push:
    branches: [ main ]

jobs:
  build-linux-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        run: |
          cat <<EOF > buildx-config.toml
          [registry."host.docker.internal:5001"]
            http = true
            insecure = true
          EOF
          docker buildx create --use --name local-builder --config buildx-config.toml
          docker buildx inspect --bootstrap

      - name: Build and Push to Local Registry
        run: |
          docker buildx build \
            --file ./dockerfile \
            --tag host.docker.internal:5001/hello:latest \
            --push \
            .